version: '3.8'

services:
  backend:
    build: ./backend
    container_name: travel-planner-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - ./backend:/app
    networks:
      - travel-planner-network

networks:
  travel-planner-network:
    driver: bridge
